name: matchms
channels:
  - defaults
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python==3.7
  - gensim==3.8.0
  - matplotlib==3.2.1
  - numba==0.48.0
  - numpy==1.18.1
  - openbabel==3.0.0
  - pandas==1.0.3
  - pip==20.0.2
  - pyteomics==4.1.2
  - pubchempy==1.0.4
  - rdkit==2019.09.3
  - scikit-learn==0.22.1
  - scipy==1.4.1
  - pip:
    - isort
    - prospector[with_pyroma]
    - pytest
    - pytest-cov
    - pycodestyle
    - ruamel.yaml
    - yapf
