name: matchms
channels:
  - defaults
  - conda-forge
dependencies:
  - pip==20.0.2
  - gensim
  - ipython
  - matplotlib
  - networkx
  - numba
  - numpy
  - openbabel==3.0.0
  - pandas
  - pubchempy
  - rdkit
  - scikit-learn
  - scipy
  - scour
  - pip:
    - pyteomics
    - community
