name: matchms
channels:
  - defaults
  - conda-forge
  - bioconda
  - nlesc
dependencies:
  - python==3.7
  - matplotlib==2.2.2
  - numpy==1.18.1
  - openbabel==3.0.0
  - pyteomics==4.1.2
  - scipy==1.4.1
  - pip:
    - isort
    - prospector[with_pyroma]
    - pytest
    - pytest-cov
    - pycodestyle
    - ruamel.yaml
    - yapf
