name: matchms
channels:
  - defaults
  - conda-forge
dependencies:
  - gensim==3.8.1
  - ipython==7.13.0
  - matplotlib==3.1.0
  - networkx==2.3
  - numba==0.44.1
  - numpy==1.16.4
  - openbabel==3.0.0
  - pandas==0.24.2
  - pubchempy==1.0.4
  - rdkit==2019.09.3
  - scikit-learn==0.22.2.post1
  - scipy==1.3.0
  - scour==0.37
  - pip:
    - pyteomics==4.2
    - community==1.0.0b1
