# Build commmand:
# conda build -c conda-forge -c bioconda -c nlesc .

{% set name = "matchms" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # git_rev: master
  # git_url: https://github.com/matchms/matchms.git
  path: .

extra:
  channels:
    - conda-forge
    - bioconda
    - nlesc

build:
  noarch: python
  number: 0
  script: {{PYTHON}} -m pip install --no-deps .

requirements:
  build:
    # dependencies only from anaconda
  host:
    - python==3.7
    - pip==20.0.2
    - setuptools
  run:
    - python==3.7
    - matplotlib==2.2.2
    - numpy==1.18.1
    - pyteomics==4.1.2
test:
  imports:
    - matchms

about:
  home: https://github.com/matchms/matchms
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Vector representation of mass spectral data (e.g. MS-MS) and spectral similarity measure. '
  description: |
    Vector representation of mass spectral data (e.g. MS-MS) and
    spectral similarity measure.
  doc_url: https://matchms.readthedocs.io/
  dev_url: https://github.com/matchms/matchms

extra:
  recipe-maintainers:
    - fdiblen
