# Build commmand:
# conda build -c conda-forge -c bioconda -c nlesc .

{% set name = "matchms" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # git_rev: master
  # git_url: https://github.com/matchms/matchms.git
  path: .

build:
  noarch: python
  number: 0
  script: {{PYTHON}} -m pip install --no-deps .

requirements:
  build:
    # dependencies only from anaconda
    - gensim==3.8.1
    - openbabel==3.0.0
    - rdkit==2019.09.3
  host:
    - python==3.7
    - pip==20.0.2
    - setuptools
  run:
    - python==3.7
    - gensim==3.8.1
    - openbabel==3.0.0
    - rdkit==2019.09.3
    - ipython==7.13.0
    - community==1.0.0b1
    - matplotlib==2.2.2
    - networkx==2.4
    - numba==0.48.0
    - numpy==1.18.1
    - pandas==1.0.3
    - pubchempy==1.0.4
    - pyteomics==4.1.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - scour==0.37
test:
  imports:
    - matchms

about:
  home: https://github.com/matchms/matchms
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Vector representation of mass spectral data (e.g. MS-MS) and spectral similarity measure. '
  description: |
    Vector representation of mass spectral data (e.g. MS-MS) and
    spectral similarity measure.
  doc_url: https://matchms.readthedocs.io/
  dev_url: https://github.com/matchms/matchms

extra:
  recipe-maintainers:
    - fdiblen
