[tool.poetry]
name = "matchms"
version = "0.21.1"
description = "Python library for large-scale comparisons and processing of tandem mass spectral data"
authors = ["matchms developer team"]
license = "Apache-2.0"
readme = "README.rst"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "<1.25"
scipy = "^1.11.1"
pandas = "^2.0.3"
pillow = "!=9.4.0"
lxml = "^4.9.3"
matplotlib = "^3.7.2"
networkx = "^3.1"
numba = "^0.57.1"
pickydict = "^0.4.0"
pyteomics = "^4.6"
requests = "^2.31.0"
sparsestack = "^0.4.1"
tqdm = "^4.65.0"
rdkit = "^2023.3.2"
pyyaml = "^6.0.1"
deprecated = "^1.2.14"


[tool.poetry.group.dev.dependencies]
decorator = "^5.1.1"
isort = "^5.12.0"
pylint = "^2.17.5"
prospector = {extras = ["with-pyroma"], version = "^1.10.2"}
pytest = "^7.4.0"
pytest-cov = "^4.1.0"
yapf = "^0.40.1"
testfixtures = "^7.1.0"

[tool.poetry.group.docs.dependencies]
sphinxcontrib-apidoc = "^0.3.0"
sphinx-rtd-theme = "^1.2.2"
sphinx = "<7"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.isort]
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
no_lines_before = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
lines_after_imports = 2
known_first_party = "matchms"
skip = "readthedocs/conf.py"


[build_sphinx]
source-dir = "docs"
build-dir = "docs/_build"
all_files = 1
builder = "html"