name: matchms-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numba >=0.47
  - numpy
  - pip
  - pyteomics >=4.2
  - requests
  - python >=3.7,<3.9
  - rdkit >=2020.03.1
  - scipy >=1.4.0
  - pip:
    - -e ..[dev]
