name: matchms-dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - numba >=0.47
  - numpy
  - pip
  - pyteomics >=4.2
  - requests
  - python >=3.7,<3.9
  - rdkit >=2020.03.1
  - scipy >=1.4.0
  - pip:
    - bump2version
    - deprecated
    - lxml
    - isort>=4.2.5,<5
    - prospector[with_pyroma]
    - pytest
    - pytest-cov
    - sphinx>=3.0.0,!=3.2.0,!=3.5.0,<4.0.0
    - sphinx_rtd_theme
    - sphinxcontrib-apidoc
    - yapf
