name: matchms
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - deprecated
  - matplotlib
  - numba >=0.47
  - numpy
  - pyteomics >=4.2
  - requests
  - python >=3.7,<3.9
  - rdkit >=2020.03.1
  - scipy >=1.4.0
