# Build commmand:
# conda build . -c conda-forge

{% set name = "matchms" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # git_rev: master
  # git_url: https://github.com/matchms/matchms.git

  path: .

requirements:
  build:
    - gensim==3.8.0
    - ipython==7.13.0
    - matplotlib==3.1.3
    - networkx==2.4
    - numba==0.48.0
    - numpy==1.18.1
    - openbabel==3.0.0
    - pandas==1.0.3
    - pip==20.0.2
    - pubchempy==1.0.4
    - rdkit==2019.09.3
    - scikit-learn==0.22.1
    - scipy==1.4.1
    - scour==0.37
    # # - pip:
    #   # Building
    #   - community==1.0.0b1
    #   - isort
    #   - prospector[with_pyroma]
    #   - pyteomics==4.2
    #   - setuptools==46.1.1
    #   - yapf
    #   # Testing
    #   - pytest<5.0.0,>=3.3.0
    #   - pytest-cookies
    #   - pycodestyle
    #   - ruamel.yaml
  host:
    - python
    - pip
  run:
    - python

test:
  # Some packages might need a `test/commands` key to check CLI.
  # List all the packages/modules that `run_test.py` imports.
  imports:
    - matchms

about:
  home: https://github.com/matchms/matchms
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Vector representation of mass spectral data (e.g. MS-MS) and spectral similarity measure. '
  description: |
    Vector representation of mass spectral data (e.g. MS-MS) and
    spectral similarity measure.
  doc_url: https://matchms.readthedocs.io/
  dev_url: https://github.com/matchms/matchms

extra:
  recipe-maintainers:
    - fdiblen
