name: 'Build matchms'

on: [push, pull_request]

jobs:

  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: matchms
          environment-file: environment.yml
          condarc-file: condarc.yml
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Check style against standards using prospector
        shell: bash -l {0}
        run: prospector -o grouped -o pylint:pylint-report.txt
      - name: Build
        shell: bash -l {0}
        run: |
          python setup.py build
      - name: Build documentation
        shell: bash -l {0}
        run: |
          make coverage html
        working-directory: readthedocs/
        env:
          SPHINXOPTS: '-n -W'  # enable nit-picky mode and turn warnings into errors
      - name: Upload documentation coverage
        if: matrix.os != 'ubuntu-latest'
        uses: actions/upload-artifact@v1
        with:
          name: documentation-coverage
          path: readthedocs/_build/coverage/python.txt
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          python setup.py test
      - name: Test with coverage
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
      - name: Correct coverage paths
        if: matrix.os == 'ubuntu-latest'
        run: sed -i "s+$PWD/++g" coverage.xml
      - name: SonarCloud Scan
        if: matrix.os == 'ubuntu-latest'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
