name: matchms

on: [push, pull_request]

jobs:

  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7', '3.8']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: matchms
          environment-file: environment.yml
          condarc-file: condarc.yml
          auto-activate-base: false
      - name: Conda info
        shell: bash -l {0}
        run: conda info
      - name: Conda list
        shell: pwsh
        run: conda list
      - name: Build
        shell: bash -l {0}
        run: |
          conda activate matchms
          python --version
          python3 setup.py build
      - name: Test
        shell: bash -l {0}
        run: |
          conda activate matchms
          python3 setup.py test
