name: Verify Bioconda Publish

on:
  schedule:
    -cron: '23 23 * * 0,4'

jobs:

  verify:
    name: verify / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.7"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: matchms-test
          auto-update-conda: true
          python-version: "3.7"
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Install the conda package from anaconda repository
        shell: bash -l {0}
        run: |
          conda install --channel bioconda --channel conda-forge matchms
      - name: List conda packages
        shell: bash -l {0}
        run: |
          conda list
      - name: Install dev dependencies to run the tests
        shell: bash -l {0}
        run: |
          conda env update --name matchms-test --file conda/environment-dev.yml
          conda info
          conda list
      - name: Run tests after installing the package
        shell: bash -l {0}
        run: |
          export TESTDIR=$RUNNER_TEMP/matchms/_test
          [ "$RUNNING_OS" = "Windows" ] && export TESTDIR=$RUNNER_TEMP\\matchms\\_test\\
          mkdir -p $TESTDIR
          cp -iRv tests integration-tests $TESTDIR
          cd $TESTDIR
          pytest --ignore="tests/test_version_string_consistency.py"
