name: Anaconda Build

on: [push, pull_request]

jobs:

  analyze:
    name: analyze / python-${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yml
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Check style against standards using prospector
        shell: bash -l {0}
        run: prospector -o grouped -o pylint:pylint-report.txt
      - name: Check whether import statements are used consistently
        shell: bash -l {0}
        run: isort --check-only --diff --conda-env matchms-dev --recursive --wrap-length 79 --lines-after-imports 2 --force-single-line --no-lines-before FUTURE --no-lines-before STDLIB --no-lines-before THIRDPARTY --no-lines-before FIRSTPARTY --no-lines-before LOCALFOLDER matchms/ tests/ integration-tests/
      - name: Build documentation
        shell: bash -l {0}
        run: |
          make coverage html
        working-directory: readthedocs/
        env:
          SPHINXOPTS: "-n"  # enable nit-picky mode
      - name: Check documentation coverage threshold
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          cat readthedocs/_build/coverage/python.txt
          UNCOVERED_MEMBERS=$(grep '*' readthedocs/_build/coverage/python.txt | wc -l)
          UNCOVERED_MEMBERS_ALLOWED=25
          if (( $UNCOVERED_MEMBERS > $UNCOVERED_MEMBERS_ALLOWED )) ; then echo "There are currently ${UNCOVERED_MEMBERS} uncovered members in the documentation, which is more than the ${UNCOVERED_MEMBERS_ALLOWED} allowed."; exit 1;fi
          echo "The code is sufficiently documented with ${UNCOVERED_MEMBERS} uncovered members out of ${UNCOVERED_MEMBERS_ALLOWED} allowed.";
      - name: Test
        if: matrix.os != 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          python setup.py test
      - name: Test with coverage
        if: matrix.os == 'ubuntu-latest'
        shell: bash -l {0}
        run: |
          pytest --cov --cov-report term --cov-report xml --junitxml=xunit-result.xml
      - name: Correct coverage paths
        if: matrix.os == 'ubuntu-latest'
        run: sed -i "s+$PWD/++g" coverage.xml
      - name: SonarCloud Scan
        if: matrix.os == 'ubuntu-latest'
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    name: build / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ["3.7"]
    runs-on: ${{ matrix.os }}
    needs: analyze
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - name: Create matchms-build environment
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-build
          auto-update-conda: true
          environment-file: conda/environment-build.yml
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env list
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Conda list
        shell: bash -l {0}
        run: conda list
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=/tmp/matchms/_build
          mkdir -p $BUILD_FOLDER
          conda build --numpy 1.18.1 --no-include-recipe \
            --channel bioconda --channel conda-forge \
            --croot $BUILD_FOLDER \
            ./conda
      - name: Upload package artifact from build
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v1
        with:
          name: conda-package-artifact
          path: /tmp/matchms/_build

  verify:
    name: verify / python-${{ matrix.python-version }} / ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    runs-on: ${{ matrix.os }}
    needs: build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Create a test environment to test the package
        uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-test
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
          conda env list
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Download conda package from build job for Unix
        if: matrix.os != 'windows-latest'
        uses: actions/download-artifact@v1
        with:
          name: conda-package-artifact
          path: /tmp/matchms/_build
      - name: Download conda package from build job for Windows
        if: matrix.os == 'windows-latest'
        uses: actions/download-artifact@v1
        with:
          name: conda-package-artifact
          path: _build
      - name: List artifact folder content for Unix
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: ls -al /tmp/matchms/_build
      - name: List artifact folder content for Windows
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        # run: ls -al "%TEMP%\matchms\_build"
        run: ls -al _build
      - name: Test local conda package on unix
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER=/tmp/matchms/_build
          conda install \
            --channel bioconda \
            --channel conda-forge \
            --channel file:/${BUILD_FOLDER}/noarch/ \
            matchms
      - name: Test the locally built conda package on Windows
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
          # set BUILD_FOLDER=file:\\%TEMP%\\matchms\\_build\\noarch\\
          conda install \
            --channel bioconda \
            --channel conda-forge \
            --channel file:\\_build \
            matchms
