name: Anaconda Publish

on:
  release:
    types: [published]

jobs:

  publish:
    name: publish / python-3.7 / ubuntu-latest
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-build
          environment-file: conda/environment-build.yml
          python-version: "3.7"
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Python info
        shell: bash -l {0}
        run: |
          which python
          python --version
      - name: Build the conda package
        shell: bash -l {0}
        run: |
          conda config --set anaconda_upload no
          export BUILD_FOLDER=/tmp/matchms/_build
          mkdir -p $BUILD_FOLDER
          conda build --numpy 1.18.1 --no-include-recipe \
            --channel bioconda --channel conda-forge \
            --croot $BUILD_FOLDER \
            ./conda
      - name: Push the package to anaconda cloud
        shell: bash -l {0}
        run: |
          export BUILD_FOLDER=/tmp/matchms/_build
          anaconda --token ${{ secrets.ANACONDA_TOKEN }} upload --user nlesc --force $BUILD_FOLDER/noarch/*.tar.bz2

  verify:
    name: verify / python-3.7 / ubuntu-latest
    runs-on: "ubuntu-latest"
    needs: publish
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: "0"
      - uses: goanpeca/setup-miniconda@v1
        with:
          activate-environment: matchms-dev
          environment-file: conda/environment-dev.yml
          channels: conda-forge,bioconda,nlesc
          python-version: "3.7"
      - name: Show conda config
        shell: bash -l {0}
        run: |
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Install the conda package from anaconda repository
        shell: bash -l {0}
        run: |
          conda install -c bioconda -c conda-forge -c nlesc matchms
      - name: Test the installed conda package
        shell: bash -l {0}
        run: |
          cd ${CONDA_PREFIX}/pkgs/matchms-*/site-packages/tests
          pytest --ignore-glob="test_version_string_consistency.py"
